/**
 * "The sheet takes over": a monthly-sheet expense row that matches a recurrence of the household (same account,
 * same normalized description) for that month does not become a second charge. It either updates the pending
 * transaction the recurrence generated, or, when the recurrence has not run yet, becomes the month's occurrence and
 * moves the recurrence on. This file finds the matches (preview and confirm use the same rules); the writes are
 * in confirmMaxFinImport.
 */
import { prisma } from '../../shared/db/prisma.js';
import { normalizeDescription } from '../recurring-transactions/detect.js';
import { anchorDayOf, dayString } from '../recurring-transactions/recurring-dates.js';
import type { MaxFinInstallment, MaxFinSectionKey } from './parsers/maxfin.types.js';

export type RecurringMatch =
  | {
      kind: 'generated';
      transactionId: string;
      recurringId: string;
      /** YYYY-MM-DD of the generated transaction. */
      day: string;
      amount: number;
      /** The generated transaction is already paid (a card occurrence, or paid by hand). */
      paid: boolean;
    }
  | {
      kind: 'recurrence';
      transactionId: null;
      recurringId: string;
      /** YYYY-MM-DD of the recurrence's nextRunAt (inside the sheet month). */
      day: string;
      followLastAmount: boolean;
      endDate: string | null;
      /** Day of month the recurrence is anchored to (its startDate day). */
      anchorDay: number;
      amount: number;
    };

/** Rows that can be taken over by a recurrence: plain expenses, not installments, not the income block. */
export function eligibleForRecurring(row: {
  type: 'INCOME' | 'EXPENSE';
  section: MaxFinSectionKey;
  installment: MaxFinInstallment | null;
}): boolean {
  return row.type === 'EXPENSE' && row.section !== 'income' && row.installment === null;
}

export function recurringMatchDetail(match: RecurringMatch): string {
  if (match.kind === 'generated') {
    return `atualiza a transação gerada de ${match.day.slice(8, 10)}/${match.day.slice(5, 7)}`;
  }
  return 'assume a recorrência e adianta a próxima execução';
}

export interface RecurringMatcher {
  /** Next unused match for the account and description (a match serves one row), or undefined. */
  take(accountId: string, description: string): RecurringMatch | undefined;
}

const NO_MATCHER: RecurringMatcher = { take: () => undefined };

/** 'YYYY-MM' prefix test on a stored day. */
function inMonth(day: string, monthKey: string): boolean {
  return day.startsWith(`${monthKey}-`);
}

/**
 * Candidates of a sheet month: (a) transactions generated by a recurrence in that month (pending, or already paid
 * by hand or because it is a card) and not taken yet (no sourceRef), then (b) active monthly recurrences whose next run falls in the month and that have no
 * transaction in it. Each is keyed by account + normalized description and handed out once, oldest first.
 */
export async function loadRecurringMatcher(
  householdId: string,
  accountIds: string[],
  monthKey: string,
): Promise<RecurringMatcher> {
  if (accountIds.length === 0) return NO_MATCHER;
  const start = new Date(Date.UTC(Number(monthKey.slice(0, 4)), Number(monthKey.slice(5, 7)) - 1, 1));
  const end = new Date(Date.UTC(Number(monthKey.slice(0, 4)), Number(monthKey.slice(5, 7)), 1));

  const generated = await prisma.transaction.findMany({
    where: {
      householdId,
      type: 'EXPENSE',
      sourceRef: null,
      recurringTransactionId: { not: null },
      accountId: { in: accountIds },
      date: { gte: start, lt: end },
    },
    select: { id: true, accountId: true, description: true, date: true, amount: true, paid: true, recurringTransactionId: true },
  });

  const recurrences = await prisma.recurringTransaction.findMany({
    where: { householdId, isActive: true, frequency: 'MONTHLY', accountId: { in: accountIds } },
    select: { id: true, accountId: true, description: true, nextRunAt: true, startDate: true, endDate: true, followLastAmount: true, amount: true },
  });
  const due = recurrences.filter((r) => inMonth(dayString(r.nextRunAt), monthKey));
  const occupied = new Set<string>();
  if (due.length > 0) {
    const present = await prisma.transaction.findMany({
      where: { householdId, recurringTransactionId: { in: due.map((r) => r.id) }, date: { gte: start, lt: end } },
      select: { recurringTransactionId: true },
    });
    for (const t of present) if (t.recurringTransactionId) occupied.add(t.recurringTransactionId);
  }

  const pools = new Map<string, RecurringMatch[]>();
  const push = (accountId: string, description: string | null, match: RecurringMatch) => {
    const key = normalizeDescription(description);
    if (!key) return;
    const id = `${accountId}|${key}`;
    const list = pools.get(id) ?? [];
    list.push(match);
    pools.set(id, list);
  };

  [...generated]
    .sort((a, b) => dayString(a.date).localeCompare(dayString(b.date)) || a.id.localeCompare(b.id))
    .forEach((t) => {
      if (!t.accountId || !t.recurringTransactionId) return;
      push(t.accountId, t.description, {
        kind: 'generated',
        transactionId: t.id,
        recurringId: t.recurringTransactionId,
        day: dayString(t.date),
        amount: t.amount.toNumber(),
        paid: t.paid,
      });
    });
  const generatedRecurrences = new Set(generated.map((t) => t.recurringTransactionId));
  [...due]
    .sort((a, b) => dayString(a.nextRunAt).localeCompare(dayString(b.nextRunAt)) || a.id.localeCompare(b.id))
    .forEach((r) => {
      if (occupied.has(r.id) || generatedRecurrences.has(r.id)) return;
      const nextRun = dayString(r.nextRunAt);
      const endDate = r.endDate ? dayString(r.endDate) : null;
      if (endDate && endDate < nextRun) return;
      push(r.accountId, r.description, {
        kind: 'recurrence',
        transactionId: null,
        recurringId: r.id,
        day: nextRun,
        followLastAmount: r.followLastAmount,
        endDate,
        anchorDay: anchorDayOf(r.startDate),
        amount: r.amount.toNumber(),
      });
    });

  if (pools.size === 0) return NO_MATCHER;
  return {
    take(accountId, description) {
      const list = pools.get(`${accountId}|${normalizeDescription(description)}`);
      if (!list || list.length === 0) return undefined;
      // Generated transactions were pushed first, so they win over recurrences that have not run.
      return list.shift();
    },
  };
}
